## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
## Creates one object matrix and cahe the inverse matrix
makeCacheMatrix <- function(x = matrix()) {
    minverse <- NULL
    set <- function(y) {
      x <<- y
      minverse <<- NULL
    }
    get <- function() x
    setinverse<- function(inverse) minverse <<-inverse
    getinverse <- function() minverse
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## Write a short comment describing this function
## Calculates the inverse matrix generated by makeCacheMatrix
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    minverse <- x$getinverse()
    if (!is.null(minverse)) {
      message("getting cached inverse matrix")
      return(minverse)
    } else {
      minverse <- solve(x$get())
      x$setinverse(minverse)
      return(minverse)
    }
  }
